metadata-version = "2015-12-19"
log-level = "debug"
interval = 10
onetime = false

[[ template ]]
source = "/etc/rancher-conf/grafana.ini.tmpl"
dest = "/etc/rancher-conf/grafana.ini"

[[ template ]]
source = "/etc/rancher-conf/get-templates.sh.tmpl"
dest = "/etc/rancher-conf/get-templates.sh"
notify-cmd = "sh /etc/rancher-conf/get-templates.sh"
notify-output = true

[[ template ]]
source = "/etc/rancher-conf/add-datasources.sh.tmpl"
dest = "/etc/rancher-conf/add-datasources.sh"
notify-cmd = "sh /etc/rancher-conf/add-datasources.sh"
notify-output = true
